stages:
  stage_01:
    cmd: python pipeline/stage_01.py
    # deps:
    #   - python pipeline/stage_01.py
    
  stage_02:
    cmd: python pipeline/stage_02.py
    # deps:
    #   - python pipeline/stage_02.py
    # outs:
    #   - artifacts/output.txt
    
  stage_03:
    cmd: python pipeline/stage_03.py
    deps:
    #   - python pipeline/stage_03.py
      - artifacts/text.txt

    